<?php
// Formula 1 drivers associative array (first 25 drivers)
$drivers = [
    [
        'position' => 1,
        'name' => 'Max Verstappen',
        'team' => 'Red Bull',
        'points' => 136,
        'wins' => 5,
        'image' => 'http://static.photos/people/200x200/10',
    ],
    [
        'position' => 2,
        'name' => 'Sergio Perez',
        'team' => 'Red Bull',
        'points' => 101,
        'wins' => 1,
        'image' => 'http://static.photos/people/200x200/11',
    ],
    [
        'position' => 3,
        'name' => 'Charles Leclerc',
        'team' => 'Ferrari',
        'points' => 98,
        'wins' => 0,
        'image' => 'http://static.photos/people/200x200/12',
    ],
    [
        'position' => 4,
        'name' => 'Carlos Sainz',
        'team' => 'Ferrari',
        'points' => 83,
        'wins' => 1,
        'image' => 'http://static.photos/people/200x200/13',
    ],
    [
        'position' => 5,
        'name' => 'Lando Norris',
        'team' => 'McLaren',
        'points' => 76,
        'wins' => 0,
        'image' => 'http://static.photos/people/200x200/14',
    ],
    
    [
        'position' => 6,
        'name' => 'Oscar Piastri',
        'team' => 'McLaren',
        'points' => 41,
        'wins' => 0,
        'image' => 'http://static.photos/people/200x200/15',
    ],
    [
        'position' => 7,
        'name' => 'George Russell',
        'team' => 'Mercedes',
        'points' => 37,
        'wins' => 0,
        'image' => 'http://static.photos/people/200x200/16',
    ],
    [
        'position' => 8,
        'name' => 'Lewis Hamilton',
        'team' => 'Mercedes',
        'points' => 27,
        'wins' => 0,
        'image' => 'http://static.photos/people/200x200/17',
    ],
    [
        'position' => 9,
        'name' => 'Fernando Alonso',
        'team' => 'Aston Martin',
        'points' => 27,
        'wins' => 0,
        'image' => 'http://static.photos/people/200x200/18',
    ],
    [
        'position' => 10,
        'name' => 'Yuki Tsunoda',
        'team' => 'RB',
        'points' => 19,
        'wins' => 0,
        'image' => 'http://static.photos/people/200x200/19',
    ],
    [
        'position' => 11,
        'name' => 'Lance Stroll',
        'team' => 'Aston Martin',
        'points' => 9,
        'wins' => 0,
        'image' => 'http://static.photos/people/200x200/20',
    ],
    [
        'position' => 12,
        'name' => 'Nico Hulkenberg',
        'team' => 'Haas',
        'points' => 6,
        'wins' => 0,
        'image' => 'http://static.photos/people/200x200/21',
    ],
    [
        'position' => 13,
        'name' => 'Oliver Bearman',
        'team' => 'Ferrari',
        'points' => 6,
        'wins' => 0,
        'image' => 'http://static.photos/people/200x200/22',
    ],
    [
        'position' => 14,
        'name' => 'Kevin Magnussen',
        'team' => 'Haas',
        'points' => 1,
        'wins' => 0,
        'image' => 'http://static.photos/people/200x200/23',
    ],
    [
        'position' => 15,
        'name' => 'Daniel Ricciardo',
        'team' => 'RB',
        'points' => 1,
        'wins' => 0,
        'image' => 'http://static.photos/people/200x200/24',
    ],
    [
        'position' => 16,
        'name' => 'Esteban Ocon',
        'team' => 'Alpine',
        'points' => 1,
        'wins' => 0,
        'image' => 'http://static.photos/people/200x200/25',
    ],
    [
        'position' => 17,
        'name' => 'Pierre Gasly',
        'team' => 'Alpine',
        'points' => 0,
        'wins' => 0,
        'image' => 'http://static.photos/people/200x200/26',
    ],
    [
        'position' => 18,
        'name' => 'Zhou Guanyu',
        'team' => 'Kick Sauber',
        'points' => 0,
        'wins' => 0,
        'image' => 'http://static.photos/people/200x200/27',
    ],
    [
        'position' => 19,
        'name' => 'Valtteri Bottas',
        'team' => 'Kick Sauber',
        'points' => 0,
        'wins' => 0,
        'image' => 'http://static.photos/people/200x200/28',
    ],
    [
        'position' => 20,
        'name' => 'Alex Albon',
        'team' => 'Williams',
        'points' => 0,
        'wins' => 0,
        'image' => 'http://static.photos/people/200x200/29',
    ],
    [
        'position' => 21,
        'name' => 'Logan Sargeant',
        'team' => 'Williams',
        'points' => 0,
        'wins' => 0,
        'image' => 'http://static.photos/people/200x200/30',
    ],
    [
        'position' => 22,
        'name' => 'Jack Doohan',
        'team' => 'Alpine',
        'points' => 0,
        'wins' => 0,
        'image' => 'http://static.photos/people/200x200/31',
    ],
    [
        'position' => 23,
        'name' => 'Felipe Drugovich',
        'team' => 'Aston Martin',
        'points' => 0,
        'wins' => 0,
        'image' => 'http://static.photos/people/200x200/32',
    ],
    [
        'position' => 24,
        'name' => 'Theo Pourchaire',
        'team' => 'Kick Sauber',
        'points' => 0,
        'wins' => 0,
        'image' => 'http://static.photos/people/200x200/33',
    ],
    [
        'position' => 25,
        'name' => 'Patricio O’Ward',
        'team' => 'McLaren',
        'points' => 0,
        'wins' => 0,
        'image' => 'http://static.photos/people/200x200/34',
    ],
];